[Feature] [WRS-1849] Publish connectors to DEV Connector Hub storage (#49)
* update pr merge action

* add publish test action

* change version for testing

* use old version

* fix changed connectors step

* test change 1

* fix action

* test change 2

* change fetch-depth

* test change 3

* fix condition

* test change 4

* ignore version bump commit

* test change 5

* use correct path to copy from

* test change 6

* list containers

* test change 7

* change connection string

* test change 8

* add version validation

* use separate step to validate version

* fix workflow file

* fix workflow file

* log versions

* remove log

* test pr validation

* re-order steps

* test validation

* test validation 2

* remove change

* update publish script to run only on changed connector

* update workflow to handle single connector change

* test 12

* use correct github env variable

* test 13

* use correct connection string

* test 14

* fix script

* test 15

* update pr merge action

* remove test action

* remove test comment

* make supportedAuth required

* remove change

* skip build and publish if no connector was changed

diff --git a/.github/workflows/pr-validation.yml b/.github/workflows/pr-validation.yml
--- a/.github/workflows/pr-validation.yml
+++ b/.github/workflows/pr-validation.yml
@@ -11,6 +11,8 @@ jobs:
     steps:
       - name: Check out code
         uses: actions/checkout@v2
+        with:
+          fetch-depth: 0
 
       - name: Get changed files
         id: files
@@ -40,6 +42,29 @@ jobs:
             fi
           done
           echo "::set-output name=connector::$connector_changed"
+      
+      - name: Ensure connector version is bumped
+        run: |
+          connector_changed=""
+          for changed_file in ${{ steps.files.outputs.all }}
+          do
+            # Extract the first tree segments of the path (e.g., src/connectors/connector-name)
+            connector_path=$(echo "$changed_file" | cut -d'/' -f1-3)
+            if [[ "$connector_path" == src/connectors/* ]]
+            then
+              # Extract the connector name (e.g., connector-name)
+              connector_name=$(echo "$connector_path" | cut -d'/' -f3)
+              if [[ -z "$connector_changed" ]]
+              then
+                MAIN_VERSION=$(git show origin/main:src/connectors/$connector_name/package.json | jq -r .version)
+                PR_VERSION=$(jq -r .version src/connectors/$connector_name/package.json)
+                if [ "$MAIN_VERSION" = "$PR_VERSION" ]; then
+                  echo "Error: The version in src/connectors/$connector_name/package.json is the same as in the main branch. Please bump the version"
+                  exit 1
+                fi
+              fi
+            fi
+          done
 
       - name: Add labels
         uses: actions-ecosystem/action-add-labels@v1
