add version validation

diff --git a/.github/workflows/pr-validation.yml b/.github/workflows/pr-validation.yml
--- a/.github/workflows/pr-validation.yml
+++ b/.github/workflows/pr-validation.yml
@@ -31,7 +31,14 @@ jobs:
               connector_name=$(echo "$connector_path" | cut -d'/' -f3)
               if [[ -z "$connector_changed" ]]
               then
-                connector_changed="$connector_name"
+                MAIN_VERSION=$(git show origin/main:src/connectors/$connector_name/package.json | jq -r .version)
+                PR_VERSION=$(jq -r .version src/connectors/$connector_name/package.json)
+                if [ "$MAIN_VERSION" = "$PR_VERSION" ]; then
+                  echo "Error: The version in src/connectors/$connector_name/package.json is the same as in the main branch. Please bump the version"
+                  exit 1
+                else
+                  connector_changed="$connector_name"
+                fi
               elif [[ "$connector_changed" != "$connector_name" ]]
               then
                 echo "Multiple connectors have been changed: $connector_changed and $connector_name. Please change only one connector per PR."
